// ESLint 10 flat config.
//
// Next's rules come from @next/eslint-plugin-next directly rather than eslint-config-next: the
// wrapper pulls in eslint-plugin-react, whose latest release still caps at ESLint 9.
//
// Two tiers, mirrored in .claude/skills:
// - must (`error`): a violation is a defect, and `npm run lint` fails.
// - should (`warn`): conventions. Warnings do not fail the build; fix the ones in code you touch.
import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import prettierConfig from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

/** Tier one: data has a declared type. Use `unknown` and narrow, never `any`. */
const mustRules = {
  '@typescript-eslint/no-explicit-any': 'error',
  '@typescript-eslint/no-empty-object-type': ['error', { allowInterfaces: 'with-single-extends' }],
  '@typescript-eslint/no-unused-expressions': ['error', { allowShortCircuit: true }],
  'react-hooks/rules-of-hooks': 'error',
};

/** Tier two: the conventions. All `warn`. */
const shouldRules = {
  // Say what a thing is.
  '@typescript-eslint/consistent-type-imports': ['warn', { prefer: 'type-imports', fixStyle: 'inline-type-imports' }],
  '@typescript-eslint/consistent-type-definitions': ['warn', 'interface'],
  '@typescript-eslint/array-type': ['warn', { default: 'array' }],
  '@typescript-eslint/no-inferrable-types': 'warn',
  '@typescript-eslint/no-non-null-assertion': 'warn',

  // Leave nothing behind.
  '@typescript-eslint/no-unused-vars': [
    'warn',
    { args: 'after-used', argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
  ],
  'no-console': ['warn', { allow: ['warn', 'error'] }],

  // Plain control flow.
  eqeqeq: ['warn', 'always', { null: 'ignore' }],
  'prefer-const': 'warn',
  'no-var': 'warn',
  'object-shorthand': ['warn', 'properties'],
  'prefer-template': 'warn',
  curly: ['warn', 'multi-line'],
  'no-else-return': ['warn', { allowElseIf: false }],
  'no-nested-ternary': 'warn',
  'no-param-reassign': ['warn', { props: false }],

  // Ceilings, not targets: crossing one is the signal to extract something.
  'max-params': ['warn', 4],
  'max-depth': ['warn', 4],
  complexity: ['warn', 15],
  'max-nested-callbacks': ['warn', 3],
  'max-lines': ['warn', { max: 500, skipBlankLines: true, skipComments: true }],
};

const NO_CLIMBING = {
  group: ['../../*'],
  message: "Two levels up is a path alias: '@/components/…', '@/lib/…'.",
};

/** Layering, as `error`: shadcn primitives (components/ui) are reached only through components/hub. */
const featureLayer = {
  'no-restricted-imports': [
    'error',
    {
      patterns: [
        NO_CLIMBING,
        {
          group: ['@/components/ui', '@/components/ui/*'],
          message:
            "Raw shadcn primitives are not for feature code. Import the wrapper from '@/components/hub/…', or run /create-hub-component to add one.",
        },
      ],
    },
  ],
};

const hubLayer = {
  'no-restricted-imports': [
    'error',
    {
      patterns: [
        NO_CLIMBING,
        {
          group: ['@/lib/actions', '@/lib/queries', '@/lib/session', '@/lib/supabase', '@/app/*'],
          message: 'A hub component renders what it is given. Take data and callbacks as props.',
        },
      ],
    },
  ],
};

export default defineConfig([
  globalIgnores(['.next/**', 'out/**', 'build/**', 'next-env.d.ts', 'design/**', 'node_modules/**']),
  {
    files: ['**/*.{ts,tsx,mts}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: {
      '@next/next': nextPlugin,
      'react-hooks': reactHooks,
      prettier: prettierPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...prettierConfig.rules,
      'prettier/prettier': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-unused-vars': 'off',
      'no-undef': 'off',
      ...mustRules,
      ...shouldRules,
      ...featureLayer,
    },
  },
  { files: ['src/components/hub/**'], rules: hubLayer },
  // Generated by the shadcn CLI; kept diffable against upstream.
  {
    files: ['src/components/ui/**'],
    rules: { 'no-restricted-imports': 'off', '@typescript-eslint/consistent-type-definitions': 'off' },
  },
]);
